#pragma once

// RGB LEDs — SK6812 (RGBW)
#define RGBLED_NUM 6
#define RGB_DI_PIN B9
#define RGBLIGHT_DRIVER SK6812           
#define SK6812_RGBW                      
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8

// Encoder
#define ENCODER_RESOLUTION 4

// Tap Dance
#define TAPPING_TERM 200

// Debounce
#define DEBOUNCE 5
